/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyLocalizedLabel.h"

#import "SBAppSwitcherBarViewDelegate-Protocol.h"
#import "SBIconDelegate-Protocol.h"

@class SBAppSwitcherBarView, SBAppSwitcherModel, SBApplicationIcon, SBNowPlayingBar, SBPrintStatusController;

@interface SBAppSwitcherController : _ABAddressBookCopyLocalizedLabel <SBIconDelegate, SBAppSwitcherBarViewDelegate>
{
    SBAppSwitcherModel *_model;
    SBNowPlayingBar *_nowPlayingBar;
    SBAppSwitcherBarView *_bottomBar;
    SBApplicationIcon *_pressedIcon;
    BOOL _editing;
    SBPrintStatusController *_printStatusController;
}

+ (id)sharedInstance;
+ (id)sharedInstanceIfAvailable;
- (id)init;
- (void)dealloc;
- (void)applicationLaunched:(id)fp8;
- (void)applicationDied:(id)fp8;
- (void)applicationSuspended:(id)fp8;
- (void)applicationsRemoved:(id)fp8 andAdded:(id)fp12;
- (void)viewWillAppear;
- (void)viewWillDisappearWithAnimationDuration:(double)fp8;
- (void)downloadsChanged:(id)fp8 withRemovals:(id)fp12;
- (void)downloadItemUpdatingStatusChanged:(id)fp8;
- (id)switcherViewForApp:(id)fp8 orientation:(int)fp12;
- (BOOL)handleMenuButtonTap;
- (BOOL)isScrolling;
- (BOOL)nowPlayingControlsVisible;
- (BOOL)airPlayControlsVisible;
- (id)applicationIconForDisplayIdentifier:(id)fp8;
- (id)_applicationIconsExcept:(id)fp8 forOrientation:(int)fp12;
- (BOOL)_inEditMode;
- (void)_beginEditing;
- (void)_stopEditing;
- (void)_removeApplicationFromRecents:(id)fp8;
- (id)_currentDownloads;
- (id)_currentIcons;
- (id)_iconForApplication:(id)fp8;
- (id)_iconForDownload:(id)fp8;
- (id)_iconForPrinting;
- (void)setNeedsPrintStatusIcon:(BOOL)fp8;
- (void)removePrintStatusIconBadge;
- (void)dismissPrintView;
- (id)printIcon;
- (BOOL)printViewIsShowing;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)iconTapped:(id)fp8;
- (BOOL)iconShouldAllowTap:(id)fp8;
- (void)iconHandleLongPress:(id)fp8;
- (void)iconTouchBegan:(id)fp8;
- (int)closeBoxTypeForIcon:(id)fp8;
- (void)iconCloseBoxTapped:(id)fp8;
- (void)appSwitcherBarRemovedFromSuperview:(id)fp8;
- (BOOL)appSwitcherBar:(id)fp8 scrollShouldCancelInContentForView:(id)fp12;
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidAppear:(int)fp12;
- (void)appSwitcherBar:(id)fp8 pageAtIndexDidDisappear:(int)fp12;
- (id)model;

@end

